# Generated by Django 4.1 on 2022-08-24 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('author_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='UserProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='Лайк')),
                ('in_bookmarks', models.BooleanField(default=False, verbose_name='Закладки')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Удовлетворительно'), (2, 'Хорошо'), (3, 'Отлично'), (4, 'Супер'), (5, 'Грандиозно')], null=True, verbose_name='Рейтинг')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отношение пользователь продукт',
                'verbose_name_plural': 'Отношение пользователи продукты',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='readers',
            field=models.ManyToManyField(related_name='products', through='store.UserProductRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
