# Generated by Django 4.1 on 2022-08-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproductrelation',
            old_name='book',
            new_name='product',
        ),
    ]
